"""empty message

Revision ID: 124ac75df1f4
Revises: 4f2fac686068
Create Date: 2015-02-14 23:04:43.275794

"""

# revision identifiers, used by Alembic.
revision = '124ac75df1f4'
down_revision = '4f2fac686068'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
