"""empty message

Revision ID: 1f85d594687f
Revises: 124ac75df1f4
Create Date: 2015-02-14 23:13:05.288245

"""

# revision identifiers, used by Alembic.
revision = '1f85d594687f'
down_revision = '124ac75df1f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
