"""empty message

Revision ID: 4f2fac686068
Revises: 19c0c5d509bb
Create Date: 2015-02-14 22:44:37.707585

"""

# revision identifiers, used by Alembic.
revision = '4f2fac686068'
down_revision = '19c0c5d509bb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('todo_is_done', sa.Boolean(), nullable=True))
    op.add_column('entries', sa.Column('todo_name', sa.String(), nullable=True))
    op.drop_column('entries', 'url')
    op.drop_column('entries', 'entries_all')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('entries_all', postgresql.JSON(), autoincrement=False, nullable=True))
    op.add_column('entries', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('entries', 'todo_name')
    op.drop_column('entries', 'todo_is_done')
    ### end Alembic commands ###
